# Generated by Django 5.2 on 2025-05-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='serviceBarbershop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='barbershop',
            name='service',
        ),
        migrations.AddField(
            model_name='barbershop',
            name='service',
            field=models.ManyToManyField(related_name='Service_Barbershop', to='barbershop.servicebarbershop'),
        ),
    ]
