# Generated by Django 5.2 on 2025-05-26 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0002_servicebarbershop_remove_barbershop_service_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='barbershop',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='barbershop',
            name='is_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
