# Generated by Django 5.2 on 2025-05-26 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0003_barbershop_employee_alter_barbershop_is_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barbershop',
            name='employee',
        ),
    ]
