# Generated by Django 5.2 on 2025-05-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariovisitante',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
