# Generated by Django 5.2 on 2025-05-26 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barbershop', '0004_remove_barbershop_employee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours', models.TimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendaUsuario', to=settings.AUTH_USER_MODEL)),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsavelService', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicoUsuario', to='barbershop.servicebarbershop')),
            ],
        ),
    ]
